state_to_district = {
    "ap": [
        "KRISHNA",
        "GUNTUR",
        "VISAKHAPATANAM",
        "CHITTOOR",
        "WEST GODAVARI",
        "EAST GODAVARI",
        "VIZIANAGARAM",
        "SPSR NELLORE",
        "Y.S.R.",
        "SRIKAKULAM",
        "ANANTAPUR",
        "KURNOOL",
        "PRAKASAM",
    ],
    "an": ["NICOBARS", "SOUTH ANDAMANS", "NORTH AND MIDDLE ANDAMAN"],
    "ar": [
        "EAST KAMENG",
        "KRA  DAADI",
        "LOHIT",
        "LOWER SUBANSIRI",
        "TIRAP",
        "WEST SIANG","UPPER SIANG",
        "CHANGLANG",
        "ANJAW",
        "DIBANG VALLEY",
        "KAMLE",
        "LONGDING",
        "PAKKE KESSANG",
        "SHI YOMI",
        "UPPER SUBANSIRI",
        "TAWANG",
        "KURUNG KUMEY",
        "LOWER SIANG",
        "NAMSAI",
        "LOWER DIBANG VALLEY",
        "SIANG",
        "PAPUM PARE",
        "LEPARADA",
        "WEST KAMENG",
        "EAST SIANG",
    ],
    "as": [
        "KOKRAJHAR",
        "WEST KARBI ANGLONG",
        "MARIGAON",
        "SONITPUR",
        "NALBARI",
        "BAKSA",
        "DIMA HASAO",
        "LAKHIMPUR",
        "DIBRUGARH",
        "DHUBRI",
        "BISWANATH",
        "DHEMAJI",
        "CHARAIDEO",
        "UDALGURI",
        "DARRANG",
        "KARIMGANJ",
        "GOALPARA",
        "KAMRUP",
        "KAMRUP METRO",
        "BARPETA",
        "GOLAGHAT",
        "TINSUKIA",
        "CACHAR",
        "CHIRANG",
        "NAGAON",
        "SIVASAGAR",
        "JORHAT",
        "HOJAI",
        "KARBI ANGLONG",
        "BONGAIGAON",
        "MAJULI",
        "HAILAKANDI",
        "SOUTH SALMARA MANCACHAR",
    ],
    "ct": [
        "DURG",
        "RAIPUR",
        "RAJNANDGAON",
        "BEMETARA",
        "BASTAR",
        "BALODA BAZAR",
        "BALOD",
        "MUNGELI",
        "SURAJPUR",
        "JANJGIR CHAMPA",
        "BILASPUR",
        "NARAYANPUR",
        "RAIGARH",
        "KORBA",
        "MAHASAMUND",
        "GAURELLA PENDRA MARWAHI",
        "KANKER",
        "KOREA",
        "KABIRDHAM",
        "JASHPUR",
        "SURGUJA",
        "BALRAMPUR",
        "DHAMTARI",
        "GARIYABAND",
        "DANTEWADA",
        "SUKMA",
        "KONDAGAON",
        "BIJAPUR",
    ],
    "dd": ["DIU", "DAMAN"],
    "ga": ["NORTH GOA", "SOUTH GOA"],
    "gj": [
        "AHMADABAD",
        "VADODARA",
        "BHAVNAGAR",
        "KACHCHH",
        "MAHESANA",
        "SURAT",
        "DEVBHUMI DWARKA",
        "GIR SOMNATH",
        "RAJKOT",
        "SABAR KANTHA",
        "PATAN",
        "ANAND",
        "MORBI",
        "AMRELI",
        "PORBANDAR",
        "BHARUCH",
        "VALSAD",
        "NAVSARI",
        "BANAS KANTHA",
        "JAMNAGAR",
        "ARVALLI",
        "SURENDRANAGAR",
        "TAPI",
        "DANG",
        "KHEDA",
        "DOHAD",
        "PANCH MAHALS",
        "JUNAGADH",
        "MAHISAGAR",
        "BOTAD",
        "CHHOTAUDEPUR",
        "NARMADA",
        "GANDHINAGAR",
    ],
    "hr": [
        "PANCHKULA",
        "SONIPAT",
        "YAMUNANAGAR",
        "KURUKSHETRA",
        "FARIDABAD",
        "HISAR",
        "KARNAL",
        "SIRSA",
        "ROHTAK",
        "JIND",
        "KAITHAL",
        "FATEHABAD",
        "PALWAL",
        "CHARKI DADRI",
        "BHIWANI",
        "JHAJJAR",
        "MAHENDRAGARH",
        "REWARI",
        "NUH",
        "AMBALA",
        "GURUGRAM",
        "PANIPAT",
    ],
    "hp": [
        "LAHUL AND SPITI",
        "MANDI",
        "SHIMLA",
        "KULLU",
        "BILASPUR",
        "SIRMAUR",
        "UNA",
        "HAMIRPUR",
        "CHAMBA",
        "KANGRA",
        "KINNAUR",
        "SOLAN",
    ],
    "jk": [
        "SRINAGAR",
        "RAJOURI",
        "UDHAMPUR",
        "SAMBA",
        "BUDGAM",
        "BARAMULLA",
        "DODA",
        "KUPWARA",
        "REASI",
        "KISHTWAR",
        "POONCH",
        "KATHUA",
        "BANDIPORA",
        "KULGAM",
        "RAMBAN",
        "PULWAMA",
        "SHOPIAN",
        "ANANTNAG",
        "GANDERBAL",
        "JAMMU",
    ],
    "jh": [
        "WEST SINGHBHUM",
        "RANCHI",
        "KODERMA",
        "RAMGARH",
        "GIRIDIH",
        "BOKARO",
        "GUMLA",
        "JAMTARA",
        "CHATRA",
        "SAHEBGANJ",
        "HAZARIBAGH",
        "SIMDEGA",
        "KHUNTI",
        "PALAMU",
        "PAKUR",
        "GARHWA",
        "SARAIKELA KHARSAWAN",
        "LATEHAR",
        "GODDA",
        "LOHARDAGA",
        "EAST SINGHBUM",
        "DEOGHAR",
        "DHANBAD",
        "DUMKA",
    ],
    "la": ["LEH LADAKH", "KARGIL"],
    "ld": ["LAKSHADWEEP DISTRICT"],
    "kl": [
        "THIRUVANANTHAPURAM",
        "KOLLAM",
        "PATHANAMTHITTA",
        "KOTTAYAM",
        "ERNAKULAM",
        "ALAPPUZHA",
        "THRISSUR",
        "PALAKKAD",
        "IDUKKI",
        "MALAPPURAM",
        "KASARAGOD",
        "KANNUR",
        "KOZHIKODE",
        "WAYANAD",
    ],
    "ka": [
        "BENGALURU RURAL",
        "BALLARI",
        "MYSURU",
        "DHARWAD",
        "UDUPI",
        "BAGALKOTE",
        "CHIKKAMAGALURU",
        "BIDAR",
        "KALABURAGI",
        "KOLAR",
        "HASSAN",
        "DAKSHINA KANNADA",
        "SHIVAMOGGA",
        "UTTARA KANNADA",
        "CHAMARAJANAGARA",
        "MANDYA",
        "TUMAKURU",
        "RAICHUR",
        "DAVANGERE",
        "KODAGU",
        "BELAGAVI",
        "KOPPAL",
        "RAMANAGARA",
        "CHITRADURGA",
        "VIJAYAPURA",
        "CHIKKABALLAPURA",
        "YADGIR",
        "GADAG",
        "HAVERI",
        "BENGALURU URBAN",
    ],
    "mp": [
        "INDORE",
        "JABALPUR",
        "RAISEN",
        "KHARGONE",
        "GWALIOR",
        "NIWARI",
        "SEHORE",
        "EAST NIMAR",
        "SHAHDOL",
        "SAGAR",
        "SATNA",
        "KATNI",
        "NARSINGHPUR",
        "BALAGHAT",
        "HOSHANGABAD",
        "UJJAIN",
        "RAJGARH",
        "BETUL",
        "MANDLA",
        "RATLAM",
        "HARDA",
        "CHHATARPUR",
        "DHAR",
        "TIKAMGARH",
        "SEONI",
        "DATIA",
        "DAMOH",
        "VIDISHA",
        "SHIVPURI",
        "NEEMUCH",
        "BARWANI",
        "DINDORI",
        "SHAJAPUR",
        "ALIRAJPUR",
        "REWA",
        "SINGRAULI",
        "BURHANPUR",
        "DEWAS",
        "MORENA",
        "CHHINDWARA",
        "AGAR MALWA",
        "ASHOKNAGAR",
        "BHIND",
        "GUNA",
        "JHABUA",
        "PANNA",
        "SHEOPUR",
        "UMARIA",
        "ANUPPUR",
        "BHOPAL",
        "SIDHI",
        "MANDSAUR",
    ],
    "mh": [
        "PUNE",
        "AMRAVATI",
        "AKOLA",
        "WASHIM",
        "SOLAPUR",
        "NAGPUR",
        "AURANGABAD",
        "MUMBAI SUBURBAN",
        "RATNAGIRI",
        "GONDIA",
        "BULDHANA",
        "CHANDRAPUR",
        "BHANDARA",
        "LATUR",
        "THANE",
        "RAIGAD",
        "YAVATMAL",
        "MUMBAI",
        "NASHIK",
        "PALGHAR",
        "BEED",
        "GADCHIROLI",
        "PARBHANI",
        "SANGLI",
        "KOLHAPUR",
        "JALNA",
        "NANDURBAR",
        "NANDED",
        "SATARA",
        "AHMEDNAGAR",
        "DHULE",
        "WARDHA",
        "SINDHUDURG",
        "HINGOLI",
        "OSMANABAD",
        "JALGAON",
    ],
    "mn": [
        "KAMJONG",
        "IMPHAL WEST",
        "IMPHAL EAST",
        "THOUBAL",
        "NONEY",
        "BISHNUPUR",
        "JIRIBAM",
        "PHERZAWL",
        "CHURACHANDPUR",
        "KAKCHING",
        "UKHRUL",
        "KANGPOKPI",
        "CHANDEL",
        "TENGNOUPAL",
        "SENAPATI",
        "TAMENGLONG",
    ],
    "mz": [
        "KOLASIB",
        "SAITUAL",
        "LUNGLEI",
        "MAMIT",
        "KHAWZAWL",
        "SERCHHIP",
        "AIZAWL",
        "HNAHTHIAL",
        "LAWNGTLAI",
        "CHAMPHAI",
        "SAIHA",
    ],
    "dn": ["DADRA AND NAGAR HAVELI"],
    "br": [
        "PATNA",
        "SAHARSA",
        "BHAGALPUR",
        "KHAGARIA",
        "JEHANABAD",
        "MUZAFFARPUR",
        "ARARIA",
        "MUNGER",
        "SUPAUL",
        "KISHANGANJ",
        "PURNIA",
        "DARBHANGA",
        "AURANGABAD",
        "KAIMUR (BHABUA)",
        "MADHEPURA",
        "NALANDA",
        "BANKA",
        "JAMUI",
        "SAMASTIPUR",
        "ROHTAS",
        "BEGUSARAI",
        "GAYA",
        "MADHUBANI",
        "ARWAL",
        "SARAN",
        "BHOJPUR",
        "PURBI CHAMPARAN",
        "SHEIKHPURA",
        "SIWAN",
        "SITAMARHI",
        "VAISHALI",
        "KATIHAR",
        "LAKHISARAI",
        "SHEOHAR",
        "BUXAR",
        "GOPALGANJ",
        "PASHCHIM CHAMPARAN",
        "NAWADA",
    ],
    "dl": [
        "EAST",
        "SOUTH",
        "CENTRAL",
        "SOUTH WEST",
        "NEW DELHI",
        "NORTH WEST",
        "WEST",
        "SOUTH EAST",
        "NORTH",
        "SHAHDARA",
        "NORTH EAST",
    ],
    "ml": [
        "NORTH GARO HILLS",
        "SOUTH WEST GARO HILLS",
        "WEST GARO HILLS",
        "EAST KHASI HILLS",
        "EAST JAINTIA HILLS",
        "EAST GARO HILLS",
        "SOUTH WEST KHASI HILLS",
        "RI BHOI",
        "WEST KHASI HILLS",
        "WEST JAINTIA HILLS",
        "SOUTH GARO HILLS",
    ],
    "nl": [
        "ZUNHEBOTO",
        "PHEK","TUENSANG",
        "PEREN",
        "DIMAPUR",
        "LONGLENG",
        "KOHIMA",
        "WOKHA",
        "KIPHIRE",
        "MON",
        "MOKOKCHUNG",
    ],
    "or": [
        "BALESHWAR",
        "KHORDHA",
        "SONEPUR",
        "ANUGUL",
        "NAYAGARH",
        "PURI",
        "BOUDH",
        "JAGATSINGHAPUR",
        "KENDUJHAR",
        "BHADRAK",
        "KENDRAPARA",
        "JAJAPUR",
        "BALANGIR",
        "KALAHANDI",
        "KANDHAMAL",
        "RAYAGADA",
        "NUAPADA",
        "BARGARH",
        "JHARSUGUDA",
        "NABARANGPUR",
        "DEOGARH",
        "KORAPUT",
        "DHENKANAL",
        "GANJAM",
        "MALKANGIRI",
        "SAMBALPUR",
        "GAJAPATI",
        "SUNDARGARH",
        "CUTTACK",
        "MAYURBHANJ",
    ],
    "py": ["KARAIKAL", "PONDICHERRY", "MAHE", "YANAM"],
    "pb": [
        "S.A.S NAGAR",
        "FATEHGARH SAHIB",
        "FARIDKOT",
        "FAZILKA",
        "RUPNAGAR",
        "JALANDHAR",
        "PATHANKOT",
        "SHAHID BHAGAT SINGH NAGAR",
        "HOSHIARPUR",
        "MANSA",
        "FIROZEPUR",
        "GURDASPUR",
        "SRI MUKTSAR SAHIB",
        "KAPURTHALA",
        "BARNALA",
        "LUDHIANA",
        "AMRITSAR",
        "SANGRUR",
        "MOGA",
        "TARN TARAN",
        "PATIALA",
        "BATHINDA",
    ],
    "rj": [
        "JAISALMER",
        "UDAIPUR",
        "BARMER",
        "CHITTORGARH",
        "JODHPUR",
        "GANGANAGAR",
        "BANSWARA",
        "SIKAR",
        "CHURU",
        "AJMER",
        "BHARATPUR",
        "HANUMANGARH",
        "JHUNJHUNU",
        "ALWAR",
        "NAGAUR",
        "DAUSA",
        "TONK",
        "JHALAWAR",
        "BARAN",
        "BUNDI",
        "PALI",
        "KOTA",
        "DHOLPUR",
        "JALORE",
        "KARAULI",
        "PRATAPGARH",
        "SAWAI MADHOPUR",
        "BIKANER",
        "DUNGARPUR",
        "RAJSAMAND",
        "SIROHI",
        "JAIPUR",
        "BHILWARA",
    ],
    "sk": ["SOUTH DISTRICT", "NORTH DISTRICT", "EAST DISTRICT", "WEST DISTRICT"],
    "tn": [
        "DINDIGUL",
        "TENKASI",
        "VIRUDHUNAGAR",
        "CHENGALPATTU",
        "THANJAVUR",
        "THENI",
        "THIRUVALLUR",
        "TIRUPPUR",
        "ERODE",
        "RANIPET",
        "CHENNAI",
        "COIMBATORE",
        "TUTICORIN",
        "NAGAPATTINAM",
        "KARUR",
        "KRISHNAGIRI",
        "SALEM",
        "SIVAGANGA",
        "TIRUCHIRAPPALLI",
        "NAMAKKAL",
        "KALLAKURICHI",
        "ARIYALUR",
        "VELLORE",
        "TIRUPATHUR",
        "PUDUKKOTTAI",
        "DHARMAPURI",
        "PERAMBALUR",
        "THE NILGIRIS",
        "KANCHIPURAM",
        "MADURAI",
        "RAMANATHAPURAM",
        "THIRUVARUR",
        "TIRUVANNAMALAI",
        "CUDDALORE",
        "KANNIYAKUMARI",
        "TIRUNELVELI",
        "VILLUPURAM",
    ],
    "tg": [
        "ADILABAD",
        "HYDERABAD",
        "SANGAREDDY",
        "RANGA REDDY",
        "MEDAK",
        "KUMURAM BHEEM ASIFABAD",
        "WARANGAL URBAN",
        "NIZAMABAD",
        "MEDCHAL MALKAJGIRI",
        "YADADRI BHUVANAGIRI",
        "KHAMMAM",
        "MAHABUBNAGAR",
        "NAGARKURNOOL",
        "KARIMNAGAR",
        "BHADRADRI KOTHAGUDEM",
        "JAGITIAL",
        "JANGOAN",
        "JAYASHANKAR BHUPALAPALLY",
        "JOGULAMBA GADWAL",
        "KAMAREDDY",
        "MAHABUBABAD",
        "MANCHERIAL",
        "MULUGU",
        "NALGONDA",
        "NARAYANPET",
        "NIRMAL",
        "PEDDAPALLI",
        "RAJANNA SIRCILLA",
        "SIDDIPET",
        "SURYAPET",
        "VIKARABAD",
        "WANAPARTHY",
        "WARANGAL RURAL",
    ],
    "tr": [
        "UNAKOTI",
        "SOUTH TRIPURA",
        "SEPAHIJALA",
        "WEST TRIPURA",
        "GOMATI",
        "DHALAI",
        "KHOWAI",
        "NORTH TRIPURA",
    ],
    "up": [
        "LUCKNOW",
        "MUZAFFARNAGAR",
        "SAHARANPUR",
        "GORAKHPUR",
        "GHAZIABAD",
        "AYODHYA",
        "PILIBHIT",
        "KHERI",
        "BASTI",
        "SONBHADRA",
        "MEERUT",
        "AMBEDKAR NAGAR",
        "DEORIA",
        "PRAYAGRAJ",
        "MAHARAJGANJ",
        "BAGHPAT",
        "BULANDSHAHR",
        "MORADABAD",
        "SIDDHARTH NAGAR",
        "JHANSI",
        "SANT KABEER NAGAR",
        "KANPUR NAGAR",
        "AMROHA",
        "BALLIA",
        "BIJNOR",
        "BARABANKI",
        "BALRAMPUR",
        "AZAMGARH",
        "BAREILLY",
        "HAPUR",
        "GONDA",
        "VARANASI",
        "GHAZIPUR",
        "SAMBHAL",
        "MAU",
        "CHANDAULI",
        "AGRA",
        "RAE BARELI",
        "SHAMLI",
        "FATEHPUR",
        "KANNAUJ",
        "JAUNPUR",
        "MATHURA",
        "BAHRAICH",
        "AMETHI",
        "MIRZAPUR",
        "RAMPUR",
        "SITAPUR",
        "PRATAPGARH",
        "SULTANPUR",
        "ALIGARH",
        "LALITPUR",
        "BANDA",
        "SHAHJAHANPUR",
        "BUDAUN",
        "KUSHI NAGAR",
        "FIROZABAD",
        "KANPUR DEHAT",
        "UNNAO",
        "CHITRAKOOT",
        "ETAH",
        "MAHOBA",
        "AURAIYA",
        "HARDOI",
        "JALAUN",
        "BHADOHI",
        "FARRUKHABAD",
        "MAINPURI",
        "SHRAVASTI",
        "ETAWAH",
        "KAUSHAMBI",
        "HAMIRPUR",
        "HATHRAS",
        "KASGANJ",
        "GAUTAM BUDDHA NAGAR",
    ],
    "ut": [
        "DEHRADUN",
        "UDAM SINGH NAGAR",
        "CHAMOLI",
        "TEHRI GARHWAL",
        "PITHORAGARH",
        "UTTAR KASHI",
        "BAGESHWAR",
        "RUDRA PRAYAG",
        "PAURI GARHWAL",
        "CHAMPAWAT",
        "HARIDWAR",
        "NAINITAL",
        "ALMORA",
    ],
    "wb": [
        "24 PARAGANAS SOUTH",
        "JHARGRAM",
        "PASCHIM BARDHAMAN",
        "DARJEELING",
        "BANKURA",
        "KOLKATA",
        "MALDAH",
        "BIRBHUM",
        "KALIMPONG",
        "COOCHBEHAR",
        "MEDINIPUR WEST",
        "JALPAIGURI",
        "HOWRAH",
        "HOOGHLY",
        "PURULIA",
        "DINAJPUR UTTAR",
        "PURBA BARDHAMAN",
        "MURSHIDABAD",
        "NADIA",
        "DINAJPUR DAKSHIN",
        "ALIPURDUAR",
        "24 PARAGANAS NORTH",
        "MEDINIPUR EAST",
    ],
}


state_code_to_name = {
    "an": "Andaman and Nicobar Islands",
    "ap": "Andhra Pradesh",
    "ar": "Arunachal Pradesh",
    "as": "Assam",
    "br": "Bihar",
    "ch": "Chandigarh",
    "ct": "Chhattisgarh",
    "dn": "Dadra and Nagar Haveli",
    "dd": "Daman and Diu",
    "dl": "Delhi",
    "ga": "Goa",
    "gj": "Gujarat",
    "hr": "Haryana",
    "hp": "Himachal Pradesh",
    "jk": "Jammu and Kashmir",
    "jh": "Jharkhand",
    "ka": "Karnataka",
    "kl": "Kerala",
    "la": "Ladakh",
    "ld": "Lakshadweep",
    "mp": "Madhya Pradesh",
    "mh": "Maharashtra",
    "mn": "Manipur",
    "ml": "Meghalaya",
    "mz": "Mizoram",
    "nl": "Nagaland",
    "or": "Odisha",
    "py": "Puducherry",
    "pb": "Punjab",
    "rj": "Rajasthan",
    "sk": "Sikkim",
    "un": "State Unassigned",
    "tn": "Tamil Nadu",
    "tg": "Telangana",
    "tr": "Tripura",
    "up": "Uttar Pradesh",
    "ut": "Uttarakhand",
    "wb": "West Bengal",    
}
state_name_to_code = {}
for k in state_code_to_name:
    state_name_to_code[state_code_to_name[k]] = k
state_names_caps = [i.upper() for i in state_name_to_code]


district_to_state = {}
for state in state_to_district:
    all_districts = state_to_district[state]
    for district in all_districts:
        district_to_state[district] = state


# these five districts are present in 2 states (for eg: an "aurangabad" in both MH & BR,"pratapgarh" in RJ & UP, etc)
duplicated_districts = [
    "AURANGABAD",
    "HAMIRPUR",
    "BALRAMPUR",
    "PRATAPGARH",
    "BILASPUR",
]


state_capitals = {
    "an": "NORTH AND MIDDLE ANDAMAN",
    "ap": "GUNTUR",
    "ar": "PAPUM PARE",
    "as": "KAMRUP METRO",
    "br": "PATNA",
    # ~ "ch": "Chandigarh",
    "ct": "RAIPUR",
    "dn": "DADRA AND NAGAR HAVELI",
    "dd": "DAMAN",
    "dl": "NEW DELHI",
    "ga": "NORTH GOA",
    "gj": "AHMADABAD",
    "hr": "PANCHKULA",
    "hp": "SHIMLA",
    "jk": "SRINAGAR",
    "jh": "RANCHI",
    "ka": "BENGALURU URBAN",
    "kl": "THIRUVANANTHAPURAM",
    "la": "LEH LADAKH",
    "ld": "LAKSHADWEEP DISTRICT",
    "mp": "BHOPAL",
    "mh": "MUMBAI",
    "mn": "IMPHAL EAST",
    "ml": "EAST KHASI HILLS",
    "mz": "AIZAWL",
    "nl": "KOHIMA",
    "or": "KHORDHA",
    "py": "PONDICHERRY",
    "pb": "S.A.S NAGAR",
    "rj": "JAIPUR",
    "sk": "EAST DISTRICT",
    "tn": "CHENNAI",
    "tg": "HYDERABAD",
    "tr": "WEST TRIPURA",
    "up": "LUCKNOW",
    "ut": "DEHRADUN",
    "wb": "KOLKATA",
}
